### ISSUE TITLE
Would be great to find it in npm registry

### ISSUE THREAD

**Issue by athieriot** [polotek/node-yammer#1]
Hi !

   My name is Aurélien Thieriot and I actually write an Hubot adapter for Yammer and your library is really useful for me !

   For now, I must include your script into my package, but it would be a lot more easier and better to just specify a dependency in my package.json file and automatically get the latest version.

   So, I wondered if you already thinking of deploy it in the official npm registry?

   If you haven't the time to do it, would you like me to take care of this? (I don't know if we can easily deal with the "author" think but still)

Thank you for your help !

Aurélien

**Comment by polotek** [comment]
Published to npm. It's version 0.1.0 and it still needs more polish. But you can now `npm install yammer`
